### ISSUE TITLE
Review MALBoK: https://www.overleaf.com/project/5c6433354b3b354faddbd7ce and provide feedback

### ISSUE THREAD

**Issue by mathiasekstedt** [mal-lang/malcompiler#7]
Someone needs to do this!!

**Comment by maxwalls** [comment]
@EngLi I think that I would prefer a separate repo for general documentation. This repo is mostly intended for complier developers and contain resources for compiler developers. A different repo could be "mal-introduction", "mal-documentation" or something along those lines. That repo can then contain educational languages, examples and resources. What do you think?

**Comment by EngLi** [comment]
Sure, if you think that is better, we can do that!
